AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  salvar-dados-sensor-iot

  Sample SAM Template for salvar-dados-sensor-iot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  SalvarDadosSensorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: salvar_dados_sensor/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SalvarDadosSensorFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt SalvarDadosSensorFunction.Arn
  SalvarDadosSensorFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt SalvarDadosSensorFunctionRole.Arn

